#!/usr/bin/env python3
# -*- coding: utf-8 -*-

########################################################################
#
#  Script to convert different structure file formats based on molsys
#
#########################################################################


import sys
import string
import molsys.mol as mol

multiassign = []
if len(sys.argv) > 2:
    multiassign = [i for i in sys.argv[2].split()]

if 'fit' in sys.argv:
    fit=True
else:
    fit=False

fi = sys.argv[1]
name  = fi.rsplit('.',1)[0]
fi_type = fi.split('.')[-1]


m = mol()
m.read(fi, ftype = fi_type)
m.addon('ff')
m.set_logger_level('DEBUG')
if multiassign != []:
    print multiassign
    if fit is True:
        m.ff.assign_multi_params(multiassign,refsysname = 'xxx')
    else:
        m.ff.assign_multi_params(multiassign)
else:
    m.ff.assign_params(['MOF-FF'])

m.ff.write(name)

