#!/usr/bin/env python
# -*- coding: utf-8 -*-

########################################################################
#
#  Script to convert different structure file formats based on molsys
#
#########################################################################


import sys
import string
import molsys.mol as mol


fi = sys.argv[1]
name  = fi.rsplit('.',1)[0]
fi_type = fi.split('.')[-1]


m = mol()
m.read(fi, ftype = fi_type)
m.addon('ff')
m.ff.assign_params('MOF-FF')
m.ff.write(name)

