#!/usr/bin/env python
# -*- coding: utf-8 -*-
###########################################
#
#   script to upload a net net to mofplus
#
###########################################


import os
import sys
import molsys
import weaver
import molsys.util.RCSR as RCSR
import mofplus


filename = sys.argv[1]


m = molsys.mol.from_file(filename)
name = m.fname.rsplit('.',1)[0]
data = RCSR.make_upload_dictionary(m,name=name)
api = mofplus.admin_api()

print 'data contains:'
for i,d in enumerate(data.keys()):
    print i,d

raw_input('continue? Ctrl+C t abort')
ret = api.add_net(data)

raw_input('update_edge_database? | should usually be done, but takes time. do only in the end Ctrl+C t abort')
api.update_edge_database()




